huazai:
  objectstorage:
    platforms:
      ali:
        accessKey: your-access-key
        secretKey: your-secret-key
        endpoint: your-oos-endpoint
        bucket: your-oos-bucketName
      tencent:
        accessKey: your-access-key
        secretKey: your-secret-key
        endpoint: your-cos-endpoint
        bucket: your-cos-bucketName
      bytedance:
        accessKey: your-access-key
        secretKey: your-secret-key
        endpoint: your-tos-endpoint
        bucket: your-cos-bucketName
