huazai:
  objectstorage:
    aliyun:
      accessKey: your-access-key
      secretKey: your-secret-key
      endpoint: your-oss-endpoint
      region: your-oss-region
      bucketName: your-cos-bucketName
    tencent:
      accessKey: your-access-key
      secretKey: your-secret-key
      endpoint: your-cos-endpoint
      region: your-cos-region
      bucketName: your-cos-bucketName
    bytedance:
      accessKey: your-access-key
      secretKey: your-secret-key
      endpoint: your-tos-endpoint
      region: your-tos-region
      bucketName: your-cos-bucketName
