huazai:
  objectstorage:
    platforms:
      ali:
        accessKey: LTAI5t7SPiLXUQhEBYUNP1kF
        secretKey: mTgjgReOgUYDZaYWMxd7atXuaevrbO
        endpoint: https://hua-zai.oss-cn-shanghai.aliyuncs.com
        bucket: hua-zai
      tencent:
        accessKey: your-access-key
        secretKey: your-secret-key
        endpoint: your-cos-endpoint
        bucket: your-cos-bucketName
      bytedance:
        accessKey: your-access-key
        secretKey: your-secret-key
        endpoint: your-tos-endpoint
        bucket: your-cos-bucketName
